<?xml version="1.0"?>

<!DOCTYPE data [
	<!ELEMENT company ((data)+)>
	<!ELEMENT data ((name,des,acceptance,favorable)+)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT des (#PCDATA)>
	<!ELEMENT acceptance (#PCDATA)>
	<!ELEMENT avgsalary (#PCDATA)>
]>



<company>
		<data>
				<name>Amazon</name>
				<des>Amazon.com, Inc. 
				often referred to as simply Amazon, is an American electronic commerce and cloud computing company with 
				headquarters in Seattle, Washington. It is the largest Internet-based retailer in the United States.
				</des>
				<acceptance>Employment Ratio : 25%</acceptance>
				<favorable>Favorable by : 85%</favorable>
				<avgsalary>Average Salary is : 20Lakhs/annum</avgsalary>
		</data>	
		
		<data>
				<name>Barclays</name>
				<des>Barclays is a British multinational banking and financial services company headquartered in London. 
				It is a universal bank with operations in retail , wholesale and investment banking, as well as wealth management, 
				mortgage lending and credit cards</des>
				<acceptance>Employment Ratio : 30%</acceptance>
				<favorable>Favorable by : 80%</favorable>
				<avgsalary>Average Salary is : 18Lakhs/annum</avgsalary>
		</data>	
		
		<data>
				<name>Kuliza</name>
				<des>Kuliza Technologies is a software product development and business consulting company with its headquarters
				at Bangalore, India. It provides business-building
				</des>
				<acceptance>Employment Ratio : 35%</acceptance>
				<favorable>Favorable by : 75%</favorable>
				<avgsalary>Average Salary is : 16Lakhs/annum</avgsalary>
		</data>	
	

		<data>
				<name>SAP</name>
				<des>SAP is enterprise resource planning software developed by the German company SAP SE. 
				SAP ERP incorporates the key business functions of an organization. 
				The latest version (SAP ERP 6.0) was made available in 2006. 
				</des>
				<acceptance>Employment Ratio : 40%</acceptance>
				<favorable>Favorable by : 70%</favorable>
				<avgsalary>Average Salary is : 14Lakhs/annum</avgsalary>
		</data>	
		
		<data>
				<name>Zomato</name>
				<des>
				Zomato is a restaurant search and discovery service founded in 2008 by Deepinder Goyal and Pankaj Chaddah. 
				It currently operates in 22 countries, including India, Australia and the United States.
				</des>
				<acceptance>Employment Ratio : 45%</acceptance>
				<favorable>Favorable by : 65%</favorable>
				<avgsalary>Average Salary is : 12Lakhs/annum</avgsalary>
		</data>	
	
</company>
